### ISSUE TITLE
Collision with Glide 4.9.0

### ISSUE THREAD

**Issue by wider2** [ct7ct7ct7/Android-VimeoPlayer#14]
if Layout contains both Vimeo and Glide o be show together
it produce such error

    java.lang.NoSuchMethodError: No virtual method priority(Lcom/bumptech/glide/Priority;)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/ee.loquiz-U2TB8USuUS9rV1afslnRTQ==/base.apk)
        at com.ct7ct7ct7.androidvimeoplayer.view.DefaultControlPanelView$11.onPostExecute(DefaultControlPanelView.java:283)
        at com.ct7ct7ct7.androidvimeoplayer.view.DefaultControlPanelView$11.onPostExecute(DefaultControlPanelView.java:262)
        at android.os.AsyncTask.finish(AsyncTask.java:727)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:744)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by minichouilleur** [comment]
I have the same issue. 
By changing Glide version from 4.9.0 to 4.8.0 in my project, it works.
@ct7ct7ct7 Please, can you upgrade Glide version to 4.9.0.

**Comment by SillyV** [comment]
I submitted a pull request with a fix for this issue, I don't know if this repo is still maintained.

**Comment by ct7ct7ct7** [comment]
Migrate to androidx. 

dependencies {
    implementation 'com.ct7ct7ct7.androidvimeoplayer:library:2.1'
}
